zfs set -r  sharenfs=rw=@172,root=@172 data/export/home
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/aa99
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/anzhang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/asmund
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/bhe
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/binwang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/binxu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/bizhang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/bjlili
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/bliu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/bliuisv
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/bozhu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/brwang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/bxia
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/bxma
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/bxsun
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/byang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/bzhang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/bzhu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/cdx86
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/cgao
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/cgzhu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/chchen
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/chenhu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/chqian
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/chuzhang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/chzhao
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/clbao
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/cli
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/cliu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/clwang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/clyuan
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/cmlu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/cnbuild
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/cuan
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/cwang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/cwwu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/cxxue
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/cyang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/cyhuang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/cyliu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/david
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/daxu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/dazhang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/default
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/dhan
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/dingwuyu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/dingwy
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/diwu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/dliang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/dma
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/dowang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/dsgong
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/duwang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/dwang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/dxiao
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/dyang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/dzhang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/efadmin
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/efnobody
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/en-tech
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/faliu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/feiwang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/feixiao
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/fgtong
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/fhyi
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/fiona
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/fkong
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/flu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/fqi
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/fqwang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/fsong
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/ftpuser
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/fumio
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/fuzhiwen
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/fywang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/galvin
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/gawang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/gbao
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/gbdu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/genghu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/ghsui
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/ghu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/ghzhang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/gjli
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/gjzhang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/gliu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/gnma
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/gpzhao
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/gshu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/guest
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/gwang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/gwen
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/gwpang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/gyli
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/gyliu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/gyye
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/gzhang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/gzhao
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/hbwang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/hdavid
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/hguo
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/hhjun
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/hma
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/hning
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/hozhang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/hq01
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/hqiao
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/hqtest
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/hrli
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/hsun
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/htliu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/htwu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/huachen
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/huawang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/hupeng
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/huzhou
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/hweng
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/hyang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/hyhe
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/hyliu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/hzhang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/isoh
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/itadmin
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/itbackup
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/jasmith
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/jbrown
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/jcui
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/jdeng
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/jdu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/jfwang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/jgao
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/jguo
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/jiangao
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/jianliu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/jiayj
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/jiazhao
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/jichen
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/jiezhou
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/jiezhu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/jijiao
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/jili
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/jili1
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/jjchen
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/jjiang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/jjiao
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/jlhuo
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/jli
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/jliu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/jmlv
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/jpchen
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/jrong
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/jsimmons
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/jsxing
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/juanwang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/jujiang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/junwang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/jxdu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/jxiu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/jxwang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/jxzhu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/jzhang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/jzhao
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/jzhong
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/jzhu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/kahuang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/kjia
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/kjiang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/klsun
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/lchen
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/lcheng
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/lcui
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/ldap1
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/ldap2
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/ldap3
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/ldap4
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/ldap5
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/lding
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/leiai
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/leishu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/leisu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/lekang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/leyang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/lfzhang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/license
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/lihan
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/liiwang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/likang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/lingxu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/linhe
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/linlu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/linsun
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/lintaobj
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/liwang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/ljchen
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/llee
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/lliang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/llliu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/lnliu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/lplin
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/lpzhang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/lqou
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/lsfadmin
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/lwang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/lwei
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/lydong
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/lye
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/lyli
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/lzhang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/mizuki
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/mkli
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/mlbao
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/mma
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/mqshou
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/mspriggs
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/mtli
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/mzhang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/mzhao
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/mzu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/nalei
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/nanqi
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/owang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/pcfang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/pchao
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/pcui
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/peiliu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/penghu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/pewang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/phjiao
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/phone
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/phpei
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/pijiang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/pliu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/pmpibot
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/ppju
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/ppxie
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/qa1
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/qa2
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/qa3
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/qa4
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/qa5
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/qbguan
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/qguo
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/qiangwu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/qiawang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/qingwu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/qinna
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/qiren
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/qjia
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/qli
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/qlnie
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/qltang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/qlyang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/qshu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/qwan
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/qwang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/qxu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/qyang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/qzhang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/qzhong
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/rchen
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/rene
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/rhuang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/rmizuki
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/rmohamme
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/root
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/rpamintu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/rpsamy
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/rshen
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/rtian
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/ruli
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/rwang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/sachin
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/sas
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/scren
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/scyu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/sfxing
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/sgyang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/sgzhang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/shawnshi
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/shxiao
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/sjwang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/sma
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/spwang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/sqi
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/sqyang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/switchos
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/sxu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/sxzhou
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/symadm
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/symadmin
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/syzhang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/szhang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/szhao
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/tadmin1
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/tadmin2
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/taoliu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/taoma
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/tempdir
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/test10
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/tfan
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/tfeng
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/tjiang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/tli
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/tlimit1
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/tllei
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/tsu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/ttang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/ttao
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/ttong
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/ttzhang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/twang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/txing
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/tyagihas
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/vmoadmin
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/wbai
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/webadmin
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/weige
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/weilin
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/weitian
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/wfzhang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/wgyan
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/whu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/wjyue
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/wli
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/wlma
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/wma
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/wnma
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/wqjin
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/wsun
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/wttang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/www
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/wwzhu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/wyding
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/wyqiu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/wyuan
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/xchuang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/xddai
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/xdwang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/xfan
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/xguo
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/xhyao
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/xianwu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/xinguo
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/xinli
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/xizhang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/xjli
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/xjma
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/xli
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/xliu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/xltang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/xlzheng
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/xmbao
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/xmgong
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/xmwang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/xpan
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/xpyi
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/xsong
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/xsun
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/xunpan
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/xwang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/xwhuang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/xwuli
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/xxin
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/xyang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/xysun
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/xyye
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/xzheng
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/yanggao
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/yanli
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/yaoliu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/yasushi
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/yayan
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/ydwang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/yfeng
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/yftest
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/ygao
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/ygaosup
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/ygwang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/yhzhang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/yinglin
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/yinokuma
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/yinzheng
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/yiwang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/yjiang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/ylshi
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/ylwu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/ymiao
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/ynqu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/yongdu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/yqdeng
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/yqwang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/yschang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/yshi
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/ytwang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/ytyuan
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/yuanfu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/yuwang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/yuzhao
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/ywang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/ywgao
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/yxguo
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/yxiao
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/yxing
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/yxu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/yyhe
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/yzhang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/yzheng
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/yzou
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/yzxie
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/zhang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/zhding
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/zhjin
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/zhjliu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/zjin
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/zjzhang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/zmzhao
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/zoyun
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/zshu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/zsli
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/zwlin
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/zwwang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/zyliu
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/zytang
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/zywen
zfs set -r  sharenfs=rw=@172,root=@172 data/export/home/zyzhou
zfs set -r  sharenfs=rw=@172,root=@172 data/export/pcc_bj2xian
zfs set -r  sharenfs=rw=@172,root=@172 data/export/pcc_cnapp
zfs set -r  sharenfs=rw=@172,root=@172 data/export/pcc_cnbuild
zfs set -r  sharenfs=rw=@172,root=@172 data/export/pcc_customenv
zfs set -r  sharenfs=rw=@172,root=@172 data/export/pcc_delivery
zfs set -r  sharenfs=rw=@172,root=@172 data/export/pcc_dev
zfs set -r  sharenfs=rw=@172,root=@172 data/export/pcc_it
zfs set -r  sharenfs=rw=@172,root=@172 data/export/pcc_local
zfs set -r  sharenfs=rw=@172,root=@172 data/export/pcc_qa
zfs set -r  sharenfs=rw=@172,root=@172 data/export/pcc_saqa
zfs set -r  sharenfs=rw=@172,root=@172 data/export/pcc_small
zfs set -r  sharenfs=rw=@172,root=@172 data/export/pcc_support
zfs set -r  sharenfs=rw=@172,root=@172 data/export/tmp_simon
